<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.(用于管理 DI 的依赖关系和类对应关系)
 *
 * @link     https://www.hyperf.io
 * @document https://hyperf.wiki
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf/hyperf/blob/master/LICENSE
 */

use Hyperf\Utils\Serializer\SerializerFactory;
use Hyperf\Utils\Serializer\Serializer;
use Hyperf\JsonRpc\JsonRpcPoolTransporter;
use Hyperf\JsonRpc\JsonRpcTransporter;

return [
    Hyperf\HttpServer\CoreMiddleware::class => App\Middleware\CoreMiddleware::class,
//    \App\Services\UserServiceInterface::class => \App\Services\UserServiceFactory::class,
    App\Services\UserServiceInterface::class => \App\Services\UserService::class,
    'UserServiceInterface1' => App\Services\UserService::class,

    'request' => Hyperf\HttpServer\Contract\RequestInterface::class,
    'http_response' => Hyperf\HttpServer\Contract\ResponseInterface::class,
//    'request' => Hyperf\HttpServer\Request::class,
//    'http_response' => Hyperf\HttpServer\Response::class,

    'encrypter' => App\Utils\Encryption\EncryptionServiceProvider::class,

    //jsonRpc 相关
    Hyperf\Contract\NormalizerInterface::class => new SerializerFactory(Serializer::class),
    JsonRpcTransporter::class => JsonRpcPoolTransporter::class,

    App\JsonRpc\Contracts\CalculatorServiceInterface::class => App\JsonRpc\Consumers\CalculatorServiceConsumer::class,

    //服务监控 自定义上报 https://hyperf.wiki/2.1/#/zh-cn/metric?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e4%b8%8a%e6%8a%a5
    Prometheus\Storage\Adapter::class => Hyperf\Metric\Adapter\Prometheus\RedisStorageFactory::class,

    'AmazonOrder' => 'App\Models\Erp\Amazon\AmazonOrder',
    'AmazonOrderItem' => 'App\Models\Erp\Amazon\AmazonOrderItem',
    'Vote' => 'App\Models\Vote',
    'VoteItem' => 'App\Models\VoteItem',
    'VoteLog' => 'App\Models\VoteLog',
    'Rank' => 'App\Models\Rank',
    'RankInit' => 'App\Models\RankInit',
    'RankDay' => 'App\Models\RankDay',
    'Customer' => 'App\Models\Customer',
    'CustomerInfo' => 'App\Models\CustomerInfo',
    'ExpLog' => 'App\Models\ExpLog',
    'CreditLog' => 'App\Models\CreditLog',
    'Subscribe' => 'App\Models\Subscribe',
    'Coupon' => 'App\Models\Coupon',
    'Product' => 'App\Models\Product',
    'customer' => 'App\Models\Customer',
    'customer_info' => 'App\Models\CustomerInfo',
    'customer_order' => 'App\Models\CustomerOrder',
    'invite_historys' => 'App\Models\InviteHistory',
    'CustomerOrder' => 'App\Models\CustomerOrder',
    'DictStore' => 'App\Models\DictStore',
    'Dict' => 'App\Models\Dict',
    'EmailHistory' => 'App\Models\EmailHistory',
    'Email' => 'App\Models\EmailHistory',
    'CouponLog' => 'App\Models\CouponLog',
    'Influencer' => 'App\Models\Redman\Influencer',
    'InviteHistory' => 'App\Models\InviteHistory',
    'Invite' => 'App\Models\InviteHistory',
    'InviteCode' => 'App\Models\InviteCode',
    'Share' => 'App\Models\Share',
    'CustomerAddress' => 'App\Models\CustomerAddress',
    'CustomerGuide' => 'App\Models\CustomerGuide',
    'CustomerSync' => 'App\Models\CustomerSync',
    'Interest' => 'App\Models\Interest',
    'Activity' => 'App\Models\Activity',
    'ActivityConfig' => 'App\Models\ActivityConfig',
    'ActivityCustomer' => 'App\Models\ActivityCustomer',
    'ActivityApply' => 'App\Models\ActivityApply',
    'ActivityApplyInfo' => 'App\Models\ActivityApplyInfo',
    'ActivityProduct' => 'App\Models\ActivityProduct',
    'ActivityProductItem' => 'App\Models\ActivityProductItem',
    'ActivityAuditLog' => 'App\Models\ActivityAuditLog',
    'ActivityHelpedLog' => 'App\Models\ActivityHelpedLog',
    'ActivityPrize' => 'App\Models\ActivityPrize',
    'ActivityPrizeItem' => 'App\Models\ActivityPrizeItem',
    'ActivityWinningLog' => 'App\Models\ActivityWinningLog',
    'ActivityShareLog' => 'App\Models\ActivityShareLog',
    'ActivityAddress' => 'App\Models\ActivityAddress',
    'ActivityBanner' => 'App\Models\ActivityBanner',
    'ApiLog' => 'App\Models\ApiLog',
    'AccessLog' => 'App\Models\Statistical\AccessLog',
    'ResponseLog' => 'App\Models\Statistical\ResponseLog',
    'SystemLog' => 'App\Models\Statistical\SystemLog',
    'Ding' => 'App\Models\Statistical\Ding',
    'Survey' => 'App\Models\Survey\Survey',
    'SurveyItem' => 'App\Models\Survey\SurveyItem',
    'SurveyItemOption' => 'App\Models\Survey\SurveyItemOption',
    'SurveyResult' => 'App\Models\Survey\SurveyResult',
    'SurveyResultItem' => 'App\Models\Survey\SurveyResultItem',
    'SurveyResultItemOption' => 'App\Models\Survey\SurveyResultItemOption',
    'ActivityClickLog' => 'App\Models\ActivityClickLog',
    'SocialMediaUser' => 'App\Models\SocialMediaUser',
    'ContactUs' => 'App\Models\ContactUs',
    'AmazonProductPrice' => 'App\Models\Erp\Amazon\AmazonProductPrice',
    'CleanoutListingDaily' => 'App\Models\Erp\Amazon\CleanoutListingDaily',
    'PointClearedLog' => 'App\Models\PointClearedLog',
    'VipBackupLog' => 'App\Models\VipBackupLog',
    'EmailStatistics' => 'App\Models\EmailStatistics',
    'CleanoutListing' => 'App\Models\Erp\Amazon\Xc\Cleanout\CleanoutListing',
    'ActivityCategory' => 'App\Models\ActivityCategory',
    'ActivityTask' => 'App\Models\ActivityTask',
    'FctOrder' => 'App\Models\Erp\Amazon\FctOrder',
    'Store' => 'App\Models\Store',
    'ActionLog' => 'App\Models\ActionLog',
    'ActivitySearch' => 'App\Models\ActivitySearch',
    'AllOrder' => 'App\Models\AllOrder',
    'RewardAsin' => 'App\Models\RewardAsin',
    'Reward' => 'App\Models\Reward',
    'Order' => 'App\Models\Order',
    'OrderItem' => 'App\Models\OrderItem',
    'OrderAddress' => 'App\Models\OrderAddress',
    'OrderReview' => 'App\Models\OrderReview',
    'PlatformOrder' => 'App\Models\Platform\Order',
    'PlatformOrderItem' => 'App\Models\Platform\OrderItem',
    'PlatformOrderClientDetail' => 'App\Models\Platform\OrderClientDetail',
    'PlatformOrderShippingAddress' => 'App\Models\Platform\OrderShippingAddress',
    'PlatformOrderBillingAddress' => 'App\Models\Platform\OrderBillingAddress',
    'PlatformFulfillment' => 'App\Models\Platform\Fulfillment',
    'PlatformFulfillmentOrderItem' => 'App\Models\Platform\FulfillmentOrderItem',
    'PlatformRefund' => 'App\Models\Platform\Refund',
    'PlatformRefundItem' => 'App\Models\Platform\RefundItem',
    'PlatformTransaction' => 'App\Models\Platform\Transaction',
    'PlatformCallbackDetail' => 'App\Models\Platform\CallbackDetail',
    'Country' => 'App\Models\Country',
    'KeyWordLog' => 'App\Models\KeyWordLog',
    'GameLog' => 'App\Models\GameLog',
    'ChanceLog' => 'App\Models\ChanceLog',
    'PlatformProduct' => 'App\Models\Platform\Product',
    'PlatformProductImage' => 'App\Models\Platform\ProductImage',
    'PlatformProductVariant' => 'App\Models\Platform\ProductVariant',
    'Theme' => 'App\Models\Platform\OnlineStore\Theme',
    'Asset' => 'App\Models\Platform\OnlineStore\Asset',
    'Page' => 'App\Models\Platform\OnlineStore\Page',
    'PagePublish' => 'App\Models\Platform\OnlineStore\PagePublish',
    'ReportLog' =>  'App\Models\Statistical\ReportLog',
    'ActivityPrizeCustomer' =>  'App\Models\ActivityPrizeCustomer',
    'UniqueId' =>  'App\Models\UniqueId',
    'ProductCountry' => 'App\Models\ProductCountry',
    'Metafield' => 'App\Models\Metafield',
    'Task' => 'App\Models\Task',
    'PlatformProductCategory' => 'App\Models\Platform\ProductCategory',
    'Category' => 'App\Models\Platform\Category',
    'ShopInfo' => 'App\Models\Erp\Amazon\ShopInfo',
    'RewardCategory' => 'App\Models\RewardCategory',
    'DimCountryAsin' => 'App\Models\Erp\Amazon\Xc\Product\DimCountryAsin',
    'BusGiftCardApply' => 'App\Models\BusGiftCardApply',
    'GiftCardApply' => 'App\Models\GiftCardApply',
    'ProductFileCategory' => 'App\Models\ProductFileCategory',
    'ProductFile' => 'App\Models\ProductFile',
    'FileUploadRecord' => 'App\Models\FileUploadRecord',
    'FileDownloadRecord' => 'App\Models\FileDownloadRecord',
    'FileItem' => 'App\Models\FileItem',
];
